app:
  name: "Mi App GFT - LOCAL"
  password: ${DB_PASSWORD:default_local_password}
  update:
    disabled: false
    message: "No se puede actualizar ahora mismo"
  pagination:
    max-size: 50
  defaults:
    name: "Usuario Anónimo"
    age: 18