app:
  name: "Mi App GFT - LOCAL"
  environment: LOCAL
  pool-size: 20
  database:
    password: ${DB_PASSWORD:default_local_password}
  update:
    disabled: false
    message: "No se puede actualizar ahora mismo"
  common:
    pagination:
      max-size: 50
    defaults:
      name: "Usuario Anónimo"
      age: 18
